# Generated by Django 3.0 on 2023-01-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginAndRegAPP', '0002_auto_20230106_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='pypie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('filling', models.CharField(max_length=45)),
                ('crust', models.CharField(max_length=45)),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pypie_user', to='LoginAndRegAPP.User')),
            ],
        ),
    ]
