# Generated by Django 4.1.5 on 2023-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalExamApp', '0002_pypie_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
