# Generated by Django 3.0 on 2023-01-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndRegAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='b_date',
        ),
    ]
